version: "3.8"

services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile.py
    image: cc7261:pyzmq
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - "5555:5555"
      - "5556:5556"

  servidorPython:
    build:
      context: .
      dockerfile: Dockerfile.py
    image: cc7261:pyzmq
    volumes:
      - ./servidorPython.py:/app/main.py
    depends_on:
      - broker

  clientePython:
    build:
      context: .
      dockerfile: Dockerfile.py
    image: cc7261:pyzmq
    volumes:
      - ./clientePython.py:/app/main.py
    depends_on:
      - broker

  servidorJava:
    build:
      context: .
      dockerfile: Dockerfile.java
    volumes:
      - ./servidorJava.java:/app/main.java
    depends_on:
      - broker

  clienteJava:
    build:
      context: .
      dockerfile: Dockerfile.java
    volumes:
      - ./clienteJava.java:/app/main.java
    depends_on:
      - broker