services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile.py
    image: broker-pyzmq:latest
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - "5555:5555"
      - "5556:5556"

  proxy:
    image: broker-pyzmq:latest
    container_name: proxy
    volumes:
      - ../proxy/proxy.py:/app/main.py
    ports:
      - "5557:5557"
      - "5558:5558"
    depends_on:
      - broker

  servidorPython:
    image: broker-pyzmq:latest
    volumes:
      - ./servidor.py:/app/main.py
      - ./data_python:/app/data
    depends_on:
      - broker
      - proxy

  clientePython:
    image: broker-pyzmq:latest
    volumes:
      - ./cliente.py:/app/main.py
    depends_on:
      - broker
      - proxy

  servidorJava:
    build:
      context: .
      dockerfile: Dockerfile.java
    image: broker-java:latest
    volumes:
      - ./servidor.java:/app/servidor.java
      - ./Message.java:/app/Message.java
      - ./Response.java:/app/Response.java
      - ./MessagePackUtil.java:/app/MessagePackUtil.java
      - ./PublicationRecord.java:/app/PublicationRecord.java
      - ./data_java:/app/data:rw
    depends_on:
      - broker
      - proxy
    command: sh -c "javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' servidor"

  clienteJava:
    image: broker-java:latest
    volumes:
      - ./cliente.java:/app/cliente.java
      - ./Message.java:/app/Message.java
      - ./Response.java:/app/Response.java
      - ./MessagePackUtil.java:/app/MessagePackUtil.java
    depends_on:
      - broker
      - proxy
      - servidorJava
      - servidorPython
    command: sh -c "javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' cliente bot-java-1"