services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile.py
    image: broker-pyzmq:latest
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - "5555:5555"
      - "5556:5556"

  proxy:
    image: broker-pyzmq:latest
    container_name: proxy
    volumes:
      - ../proxy/proxy.py:/app/main.py
    ports:
      - "5557:5557"
      - "5558:5558"
    depends_on:
      - broker

  coordinator:
    image: broker-java:latest
    container_name: coordinator
    ports:
      - "5559:5559"
    volumes:
      - ./Coordinator.java:/app/Coordinator.java
      - ./Message.java:/app/Message.java
      - ./Response.java:/app/Response.java
      - ./MessagePackUtil.java:/app/MessagePackUtil.java
      - ./ServerRecord.java:/app/ServerRecord.java
    depends_on:
      - broker
    command: sh -c "javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' Coordinator"

  # PYTHON - Desabilitado (falta implementar eleição)
  # Para ativar: remova os comentários (#) das linhas abaixo
  # servidorPython:
  #   image: broker-pyzmq:latest
  #   volumes:
  #     - ./servidor.py:/app/main.py
  #     - ./data_python:/app/data
  #   depends_on:
  #     - broker
  #     - proxy
  #     - coordinator

  # clientePython:
  #   image: broker-pyzmq:latest
  #   volumes:
  #     - ./cliente.py:/app/main.py
  #   depends_on:
  #     - broker
  #     - proxy

  servidorJava1:
    build:
      context: .
      dockerfile: Dockerfile.java
    image: broker-java:latest
    container_name: servidorJava1
    volumes:
      - ./servidor.java:/app/servidor.java
      - ./Message.java:/app/Message.java
      - ./Response.java:/app/Response.java
      - ./MessagePackUtil.java:/app/MessagePackUtil.java
      - ./PublicationRecord.java:/app/PublicationRecord.java
      - ./data_java1:/app/data:rw
      - ./ServerRecord.java:/app/ServerRecord.java
    ports:
      - "6001:6001"
    depends_on:
      - broker
      - proxy
      - coordinator
    command: sh -c "rm -f /app/*.class && javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' servidor 6001"

  servidorJava2:
    image: broker-java:latest
    container_name: servidorJava2
    volumes:
      - ./servidor.java:/app/servidor.java
      - ./Message.java:/app/Message.java
      - ./Response.java:/app/Response.java
      - ./MessagePackUtil.java:/app/MessagePackUtil.java
      - ./PublicationRecord.java:/app/PublicationRecord.java
      - ./data_java2:/app/data:rw
      - ./ServerRecord.java:/app/ServerRecord.java
    ports:
      - "6002:6002"
    depends_on:
      - broker
      - proxy
      - coordinator
      - servidorJava1
    command: sh -c "rm -f /app/*.class && javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' servidor 6002"

#  servidorJava3:
#    image: broker-java:latest
#    container_name: servidorJava3
#    volumes:
#      - ./servidor.java:/app/servidor.java
#      - ./Message.java:/app/Message.java
#      - ./Response.java:/app/Response.java
#      - ./MessagePackUtil.java:/app/MessagePackUtil.java
#      - ./PublicationRecord.java:/app/PublicationRecord.java
#      - ./data_java3:/app/data:rw
#      - ./ServerRecord.java:/app/ServerRecord.java
#    ports:
#      - "6003:6003"
#    depends_on:
#      - broker
#      - proxy
#      - coordinator
#      - servidorJava1
#      - servidorJava2
#    command: sh -c "rm -f /app/*.class && javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' servidor 6003"

#  servidorJava4:
#    image: broker-java:latest
#    container_name: servidorJava4
#    volumes:
#      - ./servidor.java:/app/servidor.java
#      - ./Message.java:/app/Message.java
#      - ./Response.java:/app/Response.java
#      - ./MessagePackUtil.java:/app/MessagePackUtil.java
#      - ./PublicationRecord.java:/app/PublicationRecord.java
#      - ./data_java3:/app/data:rw
#      - ./ServerRecord.java:/app/ServerRecord.java
#    ports:
#      - "6004:6004"
#    depends_on:
#      - broker
#      - proxy
#      - coordinator
#      - servidorJava1
#      - servidorJava2
#    command: sh -c "rm -f /app/*.class && javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' servidor 6004"

  clienteJava:
    image: broker-java:latest
    container_name: clienteJava
    volumes:
      - ./cliente.java:/app/cliente.java
      - ./Message.java:/app/Message.java
      - ./Response.java:/app/Response.java
      - ./MessagePackUtil.java:/app/MessagePackUtil.java
      - ./ServerRecord.java:/app/ServerRecord.java
    depends_on:
      - broker
      - proxy
      - coordinator
      - servidorJava1
      - servidorJava2
      - servidorJava3
     # - servidorPython
    command: sh -c "javac -cp '/app/lib/*' /app/*.java && java -cp '/app:/app/lib/*' cliente bot-java-1"